#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
		[0] = LAYOUT_split_3x5_2( // colemak
			KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_NO, \
			KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, \
			KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_BSPC, \
			KC_SPC, LT(1, KC_NO), LT(2, KC_NO), KC_ENT
		),
		[1] = LAYOUT_split_3x5_2( // symbols
			KC_NO, KC_BSLS, KC_PERC, KC_DLR, KC_NO, KC_NO, KC_CIRC, KC_LCBR, KC_RCBR, KC_NO, \
			KC_ASTR, KC_LPRN, KC_RPRN, KC_COLN, LT(4, KC_NO), KC_NO, KC_DQUO, KC_LBRC, KC_RBRC, KC_SCLN, \
			KC_NO, KC_GRV, KC_AT, KC_AMPR, KC_NO, KC_NO, KC_HASH, KC_LT, KC_GT, KC_DEL, \
			KC_NO, KC_NO, KC_ESC, KC_ENT
		),
		[2] = LAYOUT_split_3x5_2( // numbers
			KC_NO, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_PIPE, KC_MINS, KC_SLSH, KC_NO, \
			KC_DOT, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_QUOT, KC_UNDS, KC_EQL, LT(3, KC_NO), \
			KC_TILD, KC_7, KC_8, KC_9, KC_NO, KC_NO, KC_PLUS, KC_QUES, KC_EXLM, KC_DEL,
			KC_SPC, KC_0, KC_NO, KC_NO
		),
		[3] = LAYOUT_split_3x5_2( // function
			KC_NO, KC_F4, KC_F5, KC_F6, KC_F10, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_NO, \
			KC_NO, KC_F1, KC_F2, KC_F3, KC_F11, KC_MUTE, KC_MPRV, KC_MPLY, KC_MNXT, KC_NO, \
			KC_NO, KC_F7, KC_F8, KC_F9, KC_NO, KC_VOLD, KC_BRID, KC_BRIU, KC_NO, KC_NO, \
			KC_NO, KC_F12, KC_NO, KC_NO
		),
		[4] = LAYOUT_split_3x5_2( // navigation
			KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, \
			KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_NO, \
			KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, \
			KC_NO, KC_NO, KC_RCMD, KC_ROPT
		)
	};

enum combos {
  WF_TAB,
  XC_LCTL,
  UY_RSFT,
  COMMDOT_RCMD,
  SPCENT_ROPT,
  GM_CAPSWORD
};

const uint16_t PROGMEM wf_combo[] = {KC_W, KC_F, COMBO_END};
const uint16_t PROGMEM xc_combo[] = {KC_X, KC_C, COMBO_END};
const uint16_t PROGMEM uy_combo[] = {KC_U, KC_Y, COMBO_END};
const uint16_t PROGMEM commdot_combo[] = {KC_COMM, KC_DOT, COMBO_END};
const uint16_t PROGMEM spcent_combo[] = {KC_SPC, KC_ENT, COMBO_END};
const uint16_t PROGMEM gm_combo[] = {KC_G, KC_M, COMBO_END};

combo_t key_combos[] = {
  [WF_TAB] = COMBO(wf_combo, KC_TAB),
  [XC_LCTL] = COMBO(xc_combo, KC_LCTL),
  [UY_RSFT] = COMBO(uy_combo, KC_RSFT),
  [COMMDOT_RCMD] = COMBO(commdot_combo, KC_RCMD),
  [SPCENT_ROPT] = COMBO(spcent_combo, KC_ROPT),
  [GM_CAPSWORD] = COMBO_ACTION(gm_combo)
};

void process_combo_event(uint16_t combo_index, bool pressed) {
  switch(combo_index) {
    case GM_CAPSWORD:
      if (pressed) {
        caps_word_on();  // Activate Caps Word!
      }
      break;
	}
}